### ISSUE TITLE
react示例工程报错

### ISSUE THREAD

**Issue by ruyadelaosan** [openkraken/samples#5]
1、执行kraken ./build/static/js/bundle.js命令
2、发生如下报错
flutter: Observatory listening on http://127.0.0.1:62862/Q825jHYYx7k=/
undefined is not an object (evaluating 'e[Zr]')
rl@/Users/samples-main/demos/hello-react/build/static/js/bundle.js:2:51028
Lr@/Users/samples-main/demos/hello-react/build/static/js/bundle.js:2:43731
/Users/samples-main/demos/hello-react/build/static/js/bundle.js:2:43482
forEach@[native code]
Tr@/User/samples-main/demos/hello-react/build/static/js/bundle.js:2:43455
ts@/User/samples-main/demos/hello-react/build/static/js/bundle.js:2:117959
/User/samples-main/demos/hello-react/build/static/js/bundle.js:2:118731
rs@/User/samples-main/demos/hello-react/build/static/js/bundle.js:2:118759
/Users/samples-main/demos/hello-react/build/static/js/bundle.js:2:133068
n@/Users/samples-main/demos/hello-react/build/static/js/bundle.js:2:114
/Users/samples-main/demos/hello-react/build/static/js/bundle.js:2:906
global code@/Users/samples-main/demos/hello-react/build/static/js/bundle.js:2:915

flutter: Kraken DevTool listening at ws://192.168.146.127:9222
flutter: Open Chrome/Edge and paste following url to your navigator:
flutter:     devtools://devtools/bundled/inspector.html?ws=192.168.146.127:9222

**Comment by workkk98** [comment]
hello-vue项目也报错了，具体报错信息:
```
$ kraken ./dist/js/app.js

Can't find variable: SVGElement
/Users/zhanghefan/web/kraken/samples/demos/hello-vue/dist/js/app.js:10140:78
56d7@/Users/zhanghefan/web/kraken/samples/demos/hello-vue/dist/js/app.js:1184:110
__webpack_require__@/Users/zhanghefan/web/kraken/samples/demos/hello-vue/dist/js/app.js:20:34
/Users/zhanghefan/web/kraken/samples/demos/hello-vue/dist/js/app.js:97:37
__webpack_require__@/Users/zhanghefan/web/kraken/samples/demos/hello-vue/dist/js/app.js:20:34
/Users/zhanghefan/web/kraken/samples/demos/hello-vue/dist/js/app.js:84:37
global code@/Users/zhanghefan/web/kraken/samples/demos/hello-vue/dist/js/app.js:85:12
```

**Comment by Leopold1988** [comment]
hello-vue 报错如下：
```shell
flutter: Observatory listening on http://127.0.0.1:55083/tpa5mdTL0f8=/
flutter: ERROR: unexpected element type "SCRIPT"
flutter: NoSuchMethodError: The method 'send' was called on null.
Receiver: null
Tried calling: send(Instance of 'DOMUpdatedEvent')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      UIInspector.onDOMTreeChanged (package:kraken/src/inspector/ui_inspector.dart:101:38)
#2      ElementManager._debugDOMTreeChanged (package:kraken/src/dom/element_manager.dart:486:26)
#3      ElementManager.insertAdjacentNode (package:kraken/src/dom/element_manager.dart:380:5)
#4      KrakenViewController.insertAdjacentNode (package:kraken/src/launcher/controller.dart:320:21)
#5      flushUICommand (package:kraken/src/bridge/to_native.dart:393:29)
#6      initBridge.<anonymous closure>.<anonymous closure> (package:kraken/src/bridge/bridge.dart:40:9)
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
#9      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
#10     _rootRun (dart:async/zone.dart:1190:13)
#11     _CustomZone.run (dart:async/zone.dart:1093:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#13     _invoke (dart:ui/hooks.dart:251:10)
#14     _drawFrame (dart:ui/hooks.dart:209:3)
```

**Comment by wssgcg1213** [comment]
这几个问题已经修复了~ 升级到最新版本即可
