### ISSUE TITLE
hello-vue示例工程报错

### ISSUE THREAD

**Issue by siyukok** [openkraken/samples#9]
kraken cli版本号：0.8.2

➜  hello-vue git:(main) ✗ kraken dist/js/app.js
Execute binary: /Users/alias/.nvm/npm-global/lib/node_modules/@openkraken/cli/build/darwin/debug/app.app/Contents/MacOS/app 

flutter: Observatory listening on http://127.0.0.1:62677/HxKuXxHa_j4=/
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: FormatException: Invalid empty scheme (at character 1)
://:0/Users/alias/workspace/fe/samples/demos/hello-vue/dist/js/app.js
^

#0      _Uri._fail (dart:core/uri.dart:1538:5)
#1      new _Uri.notSimple (dart:core/uri.dart:1371:9)
#2      Uri.parse (dart:core/uri.dart:956:17)
#3      NetworkBundle.resolve (package:kraken/src/launcher/bundle.dart:109:56)
#4      KrakenBundle.getBundle (package:kraken/src/launcher/bundle.dart:62:18)
#5      KrakenController.loadBundle (package:kraken/src/launcher/controller.dart:689:36)
#6      launch._initKrakenApp (package:kraken/src/launcher/launcher.dart:45:22)
#7      launch._initKrakenApp (package:kraken/src/launcher/launcher.dart:34:30)
#8      launch (package:kraken/src/launcher/launcher.dart:71:25)
#9      main (package:app/main.dart:12:3)
#10     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
#11     _rootRun (dart:async/zone.dart:1354:13)
#12     _CustomZone.run (dart:async/zone.dart:1258:19)
#13     _runZoned (dart:async/zone.dart:1789:10)
#14     runZonedGuarded (dart:async/zone.dart:1777:12)
#15     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
#16     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

flutter: Kraken DevTool listening at ws://192.168.8.235:9222
flutter: Open Chrome/Edge and paste following url to your navigator:
flutter:     devtools://devtools/bundled/inspector.html?ws=192.168.8.235:9222

**Comment by answershuto** [comment]
最新的试试，这个问题已经修过了。

**Comment by wssgcg1213** [comment]
Using 0.8.3+3 or later version to solve~
